
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg
{
/// <summary>
/// UI表
/// </summary>
public partial class TbUIConfig
{
    private readonly System.Collections.Generic.Dictionary<UIType, UIConfig> _dataMap;
    private readonly System.Collections.Generic.List<UIConfig> _dataList;
    
    public TbUIConfig(JsonElement _buf)
    {
        int count = _buf.GetArrayLength();
        _dataMap = new System.Collections.Generic.Dictionary<UIType, UIConfig>(count);
        _dataList = new System.Collections.Generic.List<UIConfig>(count);
        
        foreach(JsonElement _ele in _buf.EnumerateArray())
        {
            UIConfig _v;
            _v = global::cfg.UIConfig.DeserializeUIConfig(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<UIType, UIConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<UIConfig> DataList => _dataList;

    public UIConfig GetOrDefault(UIType key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public UIConfig Get(UIType key) => _dataMap[key];
    public UIConfig this[UIType key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

