
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg
{
/// <summary>
/// UI表
/// </summary>
public sealed partial class UIConfig : Luban.BeanBase
{
    public UIConfig(JsonElement _buf) 
    {
        Id = (UIType)_buf.GetProperty("id").GetInt32();
        Path = _buf.GetProperty("path").GetString();
        Layer = _buf.GetProperty("layer").GetInt32();
    }

    public static UIConfig DeserializeUIConfig(JsonElement _buf)
    {
        return new UIConfig(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly UIType Id;
    /// <summary>
    /// 路径
    /// </summary>
    public readonly string Path;
    /// <summary>
    /// 层级
    /// </summary>
    public readonly int Layer;
   
    public const int __ID__ = 202324726;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "path:" + Path + ","
        + "layer:" + Layer + ","
        + "}";
    }
}
}

